# Generated by Django 3.0.2 on 2020-03-20 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_name', models.CharField(max_length=15)),
                ('t_question1', models.IntegerField(default=0)),
                ('t_question2', models.IntegerField(default=0)),
                ('t_question3', models.IntegerField(default=0)),
                ('t_question4', models.IntegerField(default=0)),
                ('t_question5', models.IntegerField(default=0)),
            ],
        ),
    ]
