# Generated by Django 3.0.2 on 2020-03-20 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tester',
            name='t_question1',
        ),
        migrations.RemoveField(
            model_name='tester',
            name='t_question2',
        ),
        migrations.RemoveField(
            model_name='tester',
            name='t_question3',
        ),
        migrations.RemoveField(
            model_name='tester',
            name='t_question4',
        ),
        migrations.RemoveField(
            model_name='tester',
            name='t_question5',
        ),
        migrations.AlterField(
            model_name='tester',
            name='t_name',
            field=models.CharField(max_length=100),
        ),
    ]
