# Generated by Django 3.0.2 on 2020-03-20 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testers', '0002_auto_20200320_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='tester',
            name='t_answer',
            field=models.IntegerField(default=0),
        ),
    ]
