# Generated by Django 3.0.5 on 2020-08-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200811_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='48px x 48px 크기의 png/jpg 파일을 업로드 해 주세요.', upload_to='accounts/avatar/%Y/%m/%d'),
        ),
    ]
